Trainer:
  name: null
  feature_names: [ "Conv5", ]
  feature_importance: [ 1, ]
  device: cuda
  num_batches: 200
  max_epoch: 120
  two_stage_training: false
  grad_from: null
  grad_util: null
  monitor: false

Optim:
  lr: 0.0000005
  weight_decay: 0.0

Scheduler:
  multiplier: 400
  warmup_max: 10

ContrastiveLoaderParams:
  scan_sample_num: 7
  partition_sample_num: 1
  num_workers: 8